spring:
  application:
    name: laboratory-work
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/hse
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: PerfectDB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
    baseline-on-migrate: true


server:
  port: 8094
